version: '3'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  drf-bank-web-app:
    build: .
    restart: always
    command: python /drf-bank/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/drf-bank/app
    depends_on:
      - db
    ports:
      - '8000:8000'



volumes:
  postgres_data: