# Generated by Django 4.1.7 on 2023-02-17 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=650, verbose_name='Customer account number')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bank account balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'Bank accounts',
            },
        ),
        migrations.CreateModel(
            name='TransferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categories of transfers',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_account', models.CharField(max_length=650, verbose_name="Recipient's bank account")),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount of transaction')),
                ('description', models.CharField(blank=True, max_length=5000, verbose_name='Description of transfer')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bank.transfercategory', verbose_name='Transfer category(Optional)')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.bankaccount', verbose_name='From account')),
            ],
            options={
                'verbose_name': 'transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bank.transfercategory', verbose_name='Category of transfer')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.transfer', verbose_name='Transfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
