# Generated by Django 4.1.7 on 2023-02-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_actionaddmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount of transaction'),
        ),
    ]
