# Generated by Django 4.1.7 on 2023-02-20 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bank', '0005_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount of transaction')),
                ('description', models.CharField(blank=True, max_length=5000, verbose_name='Description of transfer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.bankaccount', verbose_name='Sender')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.transfer', verbose_name='Transfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'receipt',
                'verbose_name_plural': 'Receipts',
            },
        ),
    ]
