# Generated by Django 4.1.7 on 2023-02-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0007_receipts_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={},
        ),
    ]
