# Generated by Django 4.1.7 on 2023-02-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0008_alter_bankaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'account', 'verbose_name_plural': 'Bank accounts'},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Bank.customer', verbose_name='Customer'),
        ),
    ]
