# Generated by Django 4.1.7 on 2023-02-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankUser', '0003_alter_bankuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
